// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp91zfUEXiERFB2hSz3I-iwzimUvnjw8Q',
    appId: '1:908951970253:web:8ecd26be78b0e2ff1c6484',
    messagingSenderId: '908951970253',
    projectId: 'store-app-677ac',
    authDomain: 'store-app-677ac.firebaseapp.com',
    storageBucket: 'store-app-677ac.appspot.com',
    measurementId: 'G-JGEXDS4ME3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUpIPpZJf_3U6IAZK_N0AQDPR4wkEG3KU',
    appId: '1:908951970253:android:91d15448f1e0e4671c6484',
    messagingSenderId: '908951970253',
    projectId: 'store-app-677ac',
    storageBucket: 'store-app-677ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqlD5vrcApK8MHkhKNYkprb-2xwwTdYk',
    appId: '1:908951970253:ios:6c317d2d58e38e0b1c6484',
    messagingSenderId: '908951970253',
    projectId: 'store-app-677ac',
    storageBucket: 'store-app-677ac.appspot.com',
    iosClientId: '908951970253-nk9nrllg7ro42jrnippjd66kh2n7h57m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mominApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDqlD5vrcApK8MHkhKNYkprb-2xwwTdYk',
    appId: '1:908951970253:ios:6c317d2d58e38e0b1c6484',
    messagingSenderId: '908951970253',
    projectId: 'store-app-677ac',
    storageBucket: 'store-app-677ac.appspot.com',
    iosClientId: '908951970253-nk9nrllg7ro42jrnippjd66kh2n7h57m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mominApp',
  );
}
